---
- name: COnditions in Ansible.
  hosts: remotenode
  tasks:
  - name: Checking the condition.
    ansible.builtin.command: id username
    ignore_errors: true
  - name: next statement.
    ansible.builtin.debug:
      msg: "After error statement"
...