---
- name: Installing Nginx and Starting the server.
  hosts: remotenode
  become: yes
  tasks:
  - name: Install Inginx.
    ansible.builtin.dnf:
      name: nginx
      state: latest
  - name: start nginx service.
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
...