---
- hosts: localhost
  vars:
    myname: Siva Krishna
    phone: 8888888888
  
  - name: Calling the variables.
    ansible.builtin.debug:
      msg: "Hi {{ myname }}, your phone number is {{ phone }}"
...