---
- name: Priting the message on to the console.
  hosts: localhost
  vars:
    myname: Siva Krishna
    phone: 8888888888
  tasks:
    vars: 
      muname: From Task Level
  - name: Calling the variables.
    ansible.builtin.debug:
      msg: "Hi {{ myname }}, your phone number is {{ phone }}"
...