---
- name: Priting the message on to the console.
  hosts: localhost
  var:
    myname: Siva Krishna
    phone: 8888888888
  tasks:
  - name: Calling the variables.
    ansible.builtin.debug:
      msg: "Hi {{ myname }}, your phone number is {{ phone }}"
...