---
- name: Priting the message on to the console.
  hosts: remotenode
  #vars_files:
  # - vars.yml
  #vars_prompt:
  #  - name: myname
  #    prompt: Please enter your name.
  #    private: true
  vars:
    #myname: Siva Krishna
    phone: 8888888888
  tasks:    
  - name: Calling the variables.
    #vars: 
      #myname: From Task Level
    ansible.builtin.debug:
      msg: "Hi {{ myname }}, your phone number is {{ phone }}"
...