---
- name: Priting the message on to the console.
  hosts: localhost
  vars:
    name: Siva Krishna
    phone: 8888888888
  tasks:
  - name: Calling the variables.
    ansible.builtin.debug:
      msg: "Hi {{ name }}, your phone number is {{ phone }}"
...